#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions

cleanCase
#------------------------------------------------------------------------------

#keepCases="cavity cavityGrade cavityClipped"
#loseCases="cavityFine cavityHighRe"

#for caseName in $keepCases
#do
   #11 ( cd $caseName && foamCleanTutorials )
#dne

#for caseName in $loseCases
#do
   #emoveCase $caseName

